#!/usr/bin/env bash

# -----------------------------------------------------------------
# Programmable completion specification for nfacct (netfilter.org)
#
# https://github.com/AllKind/nfacct-bash_completion
# https://sourceforge.net/projects/nfacct-bashcompletion
# -----------------------------------------------------------------

# Copyright (C) 2013-2016 Mart Frauenlob aka AllKind (AllKind@fastest.cc)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# -----------------------------------------------------------------
# Requirements:
#
# bash v4 or greater.
#
# The bash completion package version 2.0 or greater is recommended.
# https://github.com/scop/bash-completion
# -----------------------------------------------------------------

# -----------------------------------------------------------------
# Installation (quote from bash-completion README):
#
# Install it in one of the directories pointed to by
# bash-completion's pkgconfig file variables.  There are two
# alternatives: the recommended one is 'completionsdir' (get it with
# "pkg-config --variable=completionsdir bash-completion") from which
# completions are loaded on demand based on invoked commands' names,
# so be sure to name your completion file accordingly, and to include
# for example symbolic links in case the file provides completions
# for more than one command.  The other one which is present for
# backwards compatibility reasons is 'compatdir' (get it with
# "pkg-config --variable=compatdir bash-completion") from which files
# are loaded when bash_completion is loaded.
#
# For packages using GNU autotools the installation can be handled
# for example like this in configure.ac:
#
#  PKG_CHECK_VAR(bashcompdir, [bash-completion], [completionsdir], ,
#    bashcompdir="${sysconfdir}/bash_completion.d")
#  AC_SUBST(bashcompdir)
#
# ...accompanied by this in Makefile.am:
#
#  bashcompdir = @bashcompdir@
#  dist_bashcomp_DATA = # completion files go here
#
# For cmake we ship the bash-completion-config.cmake and
# bash-completion-config-version.cmake files. Example usage:
#
#  find_package(bash-completion)
#  if(BASH_COMPLETION_FOUND)
#    message(STATUS
#      "Using bash completion dir ${BASH_COMPLETION_COMPLETIONSDIR}")
#  else()
#    set (BASH_COMPLETION_COMPLETIONSDIR "/etc/bash_completion.d")
#    message (STATUS
#      "Using fallback bash completion dir ${BASH_COMPLETION_COMPLETIONSDIR}")
#  endif()
#
#  install(FILES your-completion-file DESTINATION
#    ${BASH_COMPLETION_COMPLETIONSDIR})
#
# For backwards compatibility it is still possible to put it into
# ~/.bash_completion or /etc/bash_completion.d/.
# -----------------------------------------------------------------
#
# Version 1.0
#
# -----------------------------------------------------------------

shopt -s extglob

_nfacct_complete() {
local cur prev cword words
local -i i

# main action
local str_act=""

# main parameters
local -a arr_par=( list reset add delete get flush restore version help )

# expecting _get_comp_words_by_ref() to exist from bash_completion
if declare -f _get_comp_words_by_ref &>/dev/null; then
    _get_comp_words_by_ref -n : cur prev cword words || return
else # not so neat, but a workaround
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cword=$COMP_CWORD
    for i in ${!COMP_WORDS[@]}; do words[i]="${COMP_WORDS[i]}"; done
fi

# gather information about the command line
if [[ ${words[1]} = @($(IFS='|' ;printf "%s\n" "${arr_par[*]}")) ]]; then
	str_act="${words[1]}" # this is the main parameter
fi

# here we go
COMPREPLY=()

if ((cword == 1)); then # main parameter
	COMPREPLY=( $( compgen -W '${arr_par[@]}' -- "$cur" ) )
	return 0
elif ((cword == 2)) && [[ $prev = @(delete|get) ]]; then # prev = delete/get
	while read -r; do # retrieve object table
		str_tmp="${REPLY##*=+([[:blank:]])}"
		str_tmp="${str_tmp%;}"
		COMPREPLY[${#COMPREPLY[@]}]="$str_tmp"
	done < <(command nfacct list 2>/dev/null)
	local IFS=$'\n' # to support object names with spaces
	COMPREPLY=( $( compgen -W '${COMPREPLY[@]}' -- "$cur" ) )
fi
}

complete -F _nfacct_complete nfacct

